GRANT CREATE, USAGE ON SCHEMA sso TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA sso TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sso TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA sso TO "apps";